CREATE TABLE Roles(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoleName NVARCHAR(55) NOT NULL
);

CREATE TABLE Users(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(24) NOT NULL,
Password VARCHAR(16) NOT NULL,
FullName NVARCHAR(100) NOT NULL,
RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id),
IsRegistered BIT NOT NULL,
IsBlocked BIT NOT NULL,
LastLoginDate DATE
);

CREATE TABLE Categories(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryName NVARCHAR(55) NOT NULL
);

CREATE TABLE Statuses(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
StatusName NVARCHAR(100) NOT NULL
);

CREATE TABLE Rooms(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoomNumber INT NOT NULL,
Floor INT NOT NULL,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id),
StatusId INT NOT NULL FOREIGN KEY REFERENCES Statuses(Id)
);

CREATE TABLE Clients(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ClientName NVARCHAR(100) NOT NULL
);

CREATE TABLE RoomsClients(
RoomId INT NOT NULL FOREIGN KEY REFERENCES Rooms(Id),
ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(Id),
MoveInDate DATE,
MoveOutDate DATE,
PRIMARY KEY (RoomId, ClientId)
);